name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Patch svelte config
        run: |
          sed -i "s|base: '/'|base: '/SaveItAll'|g" svelte.config.js

      - name: Patch API URL
        run: |
          sed -i "s|http://localhost:8000/api|https://saveitall-83zd.onrender.com/api|g" src/lib/api.ts

      - name: Build
        run: npm run build
        env:
          DEPLOY: true

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
